:terms:
  - :value: application/zip; ogr-format="ESRI Shapefile"
    :label: Shapefile
    :definition: ESRI Shapefile
  - :value: application/vnd.geo+json
    :label: GeoJSON
    :definition: GeoJSON
  - :value: application/geopackage+sqlite3
    :label: GeoPackage
    :definition: GPKG
