:terms:
  - :value: image/tiff; gdal-format=GTiff
    :label: GeoTIFF
    :definition: GTiff
  - :value: text/plain; gdal-format=AAIGrid
    :label: Arc/Info ASCII Grid
    :definition: AAIGrid
  - :value: application/octet-stream; gdal-format=AIG
    :label: Arc/Info Binary Grid
    :definition: AIG
  - :value: text/plain; gdal-format=USGSDEM
    :label: USGS ASCII DEM
    :definition: USGSDEM
