development:
  metadata_adapter: postgres
  storage_adapter: disk

test:
  metadata_adapter: postgres
  storage_adapter: disk

production:
  metadata_adapter: postgres
  storage_adapter: disk

staging:
  metadata_adapter: postgres
  storage_adapter: disk
